stages:
  - lint
  - build
  # - test

variables:
  POSTGRES_USER: 'bitswan_backend'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_bitswan_backend'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  DOCKER_REGISTRY: public.ecr.aws/bitswan
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE: bitswan_backend

precommit:
  stage: lint
  image: python:3.11
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

build docker:
  stage: build
  only:
    - master
    - main
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - yum install -y git
    - aws --version
    - docker --version
  script:
    - YEAR=$(date +%Y)
    - COMMIT_HASH=$(git rev-parse --short HEAD)
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:latest --build-arg COMMIT_HASH=$COMMIT_HASH --build-arg BUILD_NO=$CI_JOB_ID ./compose/production/django
    - TAG=$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH
    - IMAGE_ID=$(docker images --no-trunc -q $DOCKER_REGISTRY/$DOCKER_IMAGE:latest)
    - ID_TAG=$(echo $IMAGE_ID | sed 's/:/_/g')
    - docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:latest $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
    - docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:latest $DOCKER_REGISTRY/$DOCKER_IMAGE:$ID_TAG
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$ID_TAG
    - echo Now you can use $DOCKER_REGISTRY/$DOCKER_IMAGE:$ID_TAG in your docker-compose file.
