http:
  middlewares:
    keycloak:
      forwardAuth:
        address: http://bitswan_backend_local_traefik_forward_auth:4181
        authResponseHeaders:
        - X-Forwarded-User
        trustForwardHeader: true
  routers:
    random_deployment_id_8-admin-NAULODlSlXTpjXCTzepQfJEpbFNUDo-route:
      entryPoints:
      - web
      middlewares:
      - keycloak
      rule: Host(`random_deployment_id_8.admin.gitops-ides.bitswan.space`)
      service: random_deployment_id_8-admin-NAULODlSlXTpjXCTzepQfJEpbFNUDo-route
    to-whoami:
      entryPoints:
      - web
      middlewares:
      - keycloak
      rule: Host(`whoami.localhost`)
      service: whoami
  services:
    random_deployment_id_8-admin-NAULODlSlXTpjXCTzepQfJEpbFNUDo-route:
      loadBalancer:
        servers:
        - url: 0.0.0.0:10000
    whoami:
      loadBalancer:
        servers:
        - url: http://bitswan_backend_rathole:5202
