http:
  middlewares:
    keycloak:
      forwardAuth:
        address: http://bitswan_backend_local_traefik_forward_auth:4181
        authResponseHeaders:
        - X-Forwarded-User
        trustForwardHeader: true
  routers:
    to-whoami:
      entryPoints:
      - web
      middlewares:
      - keycloak
      rule: Host(`whoami.localhost`)
      service: whoami
  services:
    whoami:
      loadBalancer:
        servers:
        - url: http://bitswan_backend_rathole:5202
