# Generated by Django 4.2.10 on 2024-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitops', '0002_gitops_keycloak_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitops',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
