# Generated by Django 4.2.10 on 2024-03-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitops', '0003_alter_gitops_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brokers',
        ),
    ]
