# Generated by Django 4.2.10 on 2024-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardentry',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
