# Generated by Django 4.2.10 on 2024-09-13 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0002_brokers_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokers",
            name="url",
            field=models.URLField(
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["mqtt", "http", "https", "ws", "wss"]
                    )
                ]
            ),
        ),
    ]
