# Generated by Django 4.2.10 on 2024-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0009_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='keycloak_org_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
