# Generated by Django 4.2.10 on 2024-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0010_usergroup_keycloak_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNavigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('nav_items', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='broker',
        ),
        migrations.DeleteModel(
            name='Brokers',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
